show-green-chunks: false
deep-analyze: true
language: en
messages:
  en:
    player_only: "This command is for players only!"
    usage: "Usage: /ca menu"
    teleport: "Teleported to chunk [%s, %s]"
    lag_machine_warning: "Warning: Possible lag machine at [%s, %s]"
    menu_title: "Chunk Analyzer - %d"
    world_overworld: "Overworld"
    world_nether: "Nether"
    world_the_end: "The End"
    button_previous: "Previous page"
    button_next: "Next page"
    button_current_world: "Current world"

    chunk_info: "Chunk [%s, %s]"
    world: "World: %s"
    coordinates: "Coordinates: %s, %s"
    entities: "Entities: %s"
    players: "Players: %s"
    tile_entities: "Tile Entities: %s"
    armor_stands: "Armor Stands: %s"
    redstone_blocks: "Redstone blocks: %s"
    hoppers: "Hoppers: %s"
    updatable_blocks: "Updatable blocks: %s"
    light_sources: "Light sources: %s"
    load_score: "Load score: %s"
    click_to_teleport: "Click to teleport"

  ru:
    player_only: "Эта команда только для игроков!"
    usage: "Использование: /ca menu"
    teleport: "Телепортирован в чанк [%s, %s]"
    lag_machine_warning: "Предупреждение: Возможная лаг-машина в [%s, %s]"
    menu_title: "Анализатор чанков - %d"
    world_overworld: "Верхний мир"
    world_nether: "Ад"
    world_the_end: "Энд"
    button_previous: "Предыдущая страница"
    button_next: "Следующая страница"
    button_current_world: "Текущий мир"

    chunk_info: "Чанк [%s, %s]"
    world: "Мир: %s"
    coordinates: "Координаты: %s, %s"
    entities: "Сущности: %s"
    players: "Игроки: %s"
    tile_entities: "Tile Entities: %s"
    armor_stands: "Armor Stands: %s"
    redstone_blocks: "Редстоун блоки: %s"
    hoppers: "Воронки: %s"
    updatable_blocks: "Обновляемые блоки: %s"
    light_sources: "Источники света: %s"
    load_score: "Оценка нагрузки: %s"
    click_to_teleport: "Нажмите для телепортации"